import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Dumbbell, 
  Zap, 
  Brain, 
  Users, 
  TrendingUp,
  Clock,
  Heart,
  Target
} from "lucide-react";

export default function Landing() {
  const features = [
    {
      icon: Brain,
      title: "AI-Powered Planning",
      description: "Get personalized workout and nutrition plans generated by advanced AI tailored to your goals."
    },
    {
      icon: Clock,
      title: "Real-Time Tracking",
      description: "Live workout timers with audio alerts and automatic rest period notifications."
    },
    {
      icon: TrendingUp,
      title: "Progress Analytics",
      description: "Comprehensive progress tracking with detailed charts and performance insights."
    },
    {
      icon: Users,
      title: "Community Features",
      description: "Share workouts, connect with others, and get inspired by the fitness community."
    },
    {
      icon: Heart,
      title: "Nutrition Planning",
      description: "AI-generated meal plans with macro tracking and calorie monitoring."
    },
    {
      icon: Target,
      title: "Goal-Oriented",
      description: "Whether building muscle, losing fat, or improving endurance - we've got you covered."
    }
  ];

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100">
      {/* Hero Section */}
      <div className="relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="text-center">
            <div className="flex items-center justify-center space-x-3 mb-8">
              <Dumbbell className="h-16 w-16 text-primary" />
              <h1 className="text-6xl md:text-7xl font-bold bg-gradient-to-r from-blue-400 to-violet-500 bg-clip-text text-transparent">
                FitForge AI
              </h1>
            </div>
            <p className="text-xl md:text-2xl text-slate-400 mb-8 max-w-3xl mx-auto">
              Your Personal AI Fitness Planner - Transform your fitness journey with AI-powered workout plans, 
              real-time tracking, and intelligent nutrition guidance.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Button 
                size="lg" 
                className="text-lg px-8 py-4"
                onClick={() => window.location.href = '/api/login'}
              >
                <Zap className="mr-2 h-5 w-5" />
                Start Your Journey
              </Button>
              <p className="text-sm text-slate-500">
                Sign in with your Google account to get started
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-slate-100 mb-4">
            Everything you need to reach your fitness goals
          </h2>
          <p className="text-xl text-slate-400 max-w-2xl mx-auto">
            Comprehensive tools and AI-powered insights to optimize your fitness journey
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card key={index} className="bg-slate-800 border-slate-700 hover:border-slate-600 transition-colors">
                <CardContent className="p-6">
                  <div className="flex items-center space-x-4 mb-4">
                    <div className="w-12 h-12 bg-primary/20 rounded-lg flex items-center justify-center">
                      <Icon className="h-6 w-6 text-primary" />
                    </div>
                    <h3 className="text-xl font-semibold text-slate-100">{feature.title}</h3>
                  </div>
                  <p className="text-slate-400">{feature.description}</p>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-slate-800 border-t border-slate-700">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-slate-100 mb-4">
              Ready to forge your fitness future?
            </h2>
            <p className="text-lg text-slate-400 mb-8 max-w-2xl mx-auto">
              Join thousands of users who have transformed their fitness journey with FitForge AI.
            </p>
            <Button 
              size="lg" 
              className="text-lg px-8 py-4"
              onClick={() => window.location.href = '/api/login'}
            >
              Get Started Now
            </Button>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-slate-900 border-t border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center text-slate-500 text-sm">
            <p>&copy; {new Date().getFullYear()} FitForge AI. Unleash your potential.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
